function [fitresult, gof] = createFitT10(plateau_average, plateau_fitted_average, errors, I_supply, fitted_raw, meas_results_txt, plot_bool,plots_folder_path)
%CREATEFIT(ABS_PLATEAU_AVERAGE,ABS_PLATEAUS_SC_AVERAGE,WEIGHT)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: abs_plateau_average
%      Y Output: abs_plateaus_SC_average
%      Weights: weight
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Feb-2024 18:56:16

%% error definition
abs_plateau_average = abs(plateau_average);
abs_plateau_fitted_average = abs(plateau_fitted_average);
weight = errors.^-2;
for i = 1:length(weight)
    if weight(i) == inf
        vector_correction = [0.001,  0.002];
        weight(i) = std(vector_correction);
    end
end

%% Fit: 'untitled fit 1'.
% [xData, yData, weights] = prepareCurveData( abs_plateau_average, abs_plateau_fitted_average, weight);
[xData, yData, weights] = prepareCurveData( abs_plateau_average, abs_plateau_fitted_average, weight);

% Set up fittype and options.
ft = fittype( '(100*10^-3)*1.92*abs(I/I_c)^(n)', 'independent', 'I', 'dependent', 'V' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Lower = [1e-10 1e-10];
opts.Display = 'Off';
opts.StartPoint = [0.438744359656398 0.381558457093008];
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

%% Store the coefficient values in a proper variable
coeff_values = coeffvalues(fitresult);
I_c_value = coeff_values(1); % I_c is the first coefficient
n_value = coeff_values(2); % n is the second coefficient

%% Create the Title
title_str = sprintf('Rsquare = %f, I_c = %.2f [A], n = %.2f', gof.rsquare, I_c_value, n_value);

%% save results into a txt
fprintf(meas_results_txt, 'T10\t%f\t%f\t%f\n', I_c_value, n_value, gof.rsquare);

%% Plot fit with data.
if plot_bool == 1

    figure( 'Name', 'untitled fit 1' );
    hold on
    title(title_str);
    plot(I_supply, fitted_raw,'o', 'MarkerEdgeColor', [0.8 0.8 0.8])
    errorbar(plateau_average, plateau_fitted_average, errors, '.')
    h = plot( fitresult, xData, yData );
    legend( h, 'abs_plateaus_T10_average vs. abs_plateau_average with weight', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
    % Label axes
    xlabel( 'abs_plateau_average', 'Interpreter', 'none' );
    ylabel( 'abs_plateaus_SC_average', 'Interpreter', 'none' );
    % axes limiter
    ylim([-6,25]);
    xlim([0, 85]);
    grid on
        % Specify a custom filename
    file_name = 'T10Fit.fig';
    
    % Full file path (combine folder and filename)
    full_path = fullfile(plots_folder_path, file_name);
    
    % Save the plot in .fig format
    savefig(full_path);
end 


