function [fitresult_mod, gof_mod] = PowerlawModFitRamp(I_supply_nonrep, SC_mV_nonrep, meas_results_txt,plots_folder_path)
%CREATEFIT(I_SUPPLY_NONREP,SC_MV_NONREP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: I_supply_nonrep
%      Y Output: SC_mV_nonrep
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Mar-2024 15:17:30


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( I_supply_nonrep, SC_mV_nonrep );

% Set up fittype and options.
ft = fittype( '(100*10^-3)*6*(abs(I/(98.76+m_I*I)))^(29.34+m_n*I)', 'independent', 'I', 'dependent', 'V' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.83 0.47];
opts.Upper = [1e-10 Inf];

% Fit model to data.
[fitresult_mod, gof_mod] = fit( xData, yData, ft, opts );

%% Store the coefficient values in a proper variable
coeff_values = coeffvalues(fitresult_mod);
m_I_value = coeff_values(1); % I_c is the first coefficient
m_n_value = coeff_values(2); % n is the second coefficient

%% compute I_c and n
V = (V_th.*(I_supply_nonrep./(I_0+m_I_value.*I_supply_nonrep)).^(n_0+m_n_value.*I_supply_nonrep));
V_diff = abs(V - V_th);
[V_diff_min, V_diff_min_index] = min(V_diff);
I_c = I_0+m_I_value*I_supply_nonrep(V_diff_min_index);
n = n_0+m_n_value*I_supply_nonrep(V_diff_min_index);

%% save results into a txt
fprintf(meas_results_txt, 'SC\t%f\t%f\t%f\n', I_c, n, gof_mod.rsquare);

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'SC_mV_nonrep vs. I_supply_nonrep', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'I_supply_nonrep', 'Interpreter', 'none' );
ylabel( 'SC_mV_nonrep', 'Interpreter', 'none' );
grid on
    % Specify a custom filename
    file_name = 'SC_ramp_fit.fig';
    
    % Full file path (combine folder and filename)
    full_path = fullfile(plots_folder_path, file_name);
    
    % Save the plot in .fig format
    savefig(full_path);

